<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SwitchPoint.Domain\SwitchPoint.Domain.csproj" />
    <ProjectReference Include="..\SwitchPoint.Calculation\SwitchPoint.Calculation.csproj" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>

</Project>
